modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/YourUser/toughasmekanism/issues"

[[mods]]
modId="toughasmekanism"
version="1.0-SNAPSHOT"
displayName="Tough as Mekanism"
description="Integrates Tough As Nails with Mekanism."

# Minecraft依存関係
[[dependencies.toughasmekanism]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"

# Forge依存関係
[[dependencies.toughasmekanism]]
modId="forge"
mandatory=true
versionRange="[40.2.21]"
ordering="NONE"
side="BOTH"

# Tough As Nails依存関係
[[dependencies.toughasmekanism]]
modId="toughasnails"
mandatory=true
versionRange="[7.0.0.73]"
ordering="NONE"
side="BOTH"

# Mekanism依存関係
[[dependencies.toughasmekanism]]
modId="mekanism"
mandatory=true
versionRange="[10.2.5.465,)"
ordering="NONE"
side="BOTH"